/*
 * Copyright (C) 2018-2019 ERS - Alejandro Villalobos Hernandez (alevilla86@hotmail.com). All rights reserved.
 */
package com.ers.core.orm;
// Generated Mar 20, 2018 9:55:08 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserJoinEventId generated by hbm2java
 */
@Embeddable
public class UserJoinEventId implements java.io.Serializable {

    private String userId;
    private String eventId;

    public UserJoinEventId() {
    }

    public UserJoinEventId(String userId, String eventId) {
        this.userId = userId;
        this.eventId = eventId;
    }

    @Column(name = "user_id", nullable = false, length = 36)
    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Column(name = "event_id", nullable = false, length = 36)
    public String getEventId() {
        return this.eventId;
    }

    public void setEventId(String eventId) {
        this.eventId = eventId;
    }

    @Override
    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof UserJoinEventId)) {
            return false;
        }
        UserJoinEventId castOther = (UserJoinEventId) other;

        return ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null && castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())))
                && ((this.getEventId() == castOther.getEventId()) || (this.getEventId() != null && castOther.getEventId() != null && this.getEventId().equals(castOther.getEventId())));
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
        result = 37 * result + (getEventId() == null ? 0 : this.getEventId().hashCode());
        return result;
    }

}
