package com.ers.core.orm;
// Generated Mar 20, 2018 9:55:08 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserJoinEvent generated by hbm2java
 */
@Entity
@Table(name = "user_join_event")
public class UserJoinEvent implements java.io.Serializable {

    private UserJoinEventId id;
    private User user;
    private Event event;
    private Date dateRegistered;
    private double amountPaid;
    private Currency currency;
    private String registeredByUserId;
    private String registeredByUserEmail;

    public UserJoinEvent() {
    }

    @EmbeddedId
    @AttributeOverrides({
        @AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false, length = 36)),
        @AttributeOverride(name = "eventId", column = @Column(name = "event_id", nullable = false, length = 36))})
    public UserJoinEventId getId() {
        return this.id;
    }

    public void setId(UserJoinEventId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false, insertable = false, updatable = false)
    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "event_id", nullable = false, insertable = false, updatable = false)
    public Event getEvent() {
        return this.event;
    }

    public void setEvent(Event event) {
        this.event = event;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "date_registered", nullable = false, length = 19)
    public Date getDateRegistered() {
        return this.dateRegistered;
    }

    public void setDateRegistered(Date dateRegistered) {
        this.dateRegistered = dateRegistered;
    }

    @Column(name = "amount_paid", nullable = false, precision = 22, scale = 0)
    public double getAmountPaid() {
        return this.amountPaid;
    }

    public void setAmountPaid(double amountPaid) {
        this.amountPaid = amountPaid;
    }

    @Enumerated(EnumType.STRING)
    @Column(name = "currency", nullable = false, length = 4)
    public Currency getCurrency() {
        return currency;
    }

    public void setCurrency(Currency currency) {
        this.currency = currency;
    }

    @Column(name = "registered_by_user_id", nullable = false, length = 36)
    public String getRegisteredByUserId() {
        return this.registeredByUserId;
    }

    public void setRegisteredByUserId(String registeredByUserId) {
        this.registeredByUserId = registeredByUserId;
    }

    @Column(name = "registered_by_user_email", nullable = false, length = 128)
    public String getRegisteredByUserEmail() {
        return this.registeredByUserEmail;
    }

    public void setRegisteredByUserEmail(String registeredByUserEmail) {
        this.registeredByUserEmail = registeredByUserEmail;
    }

}
